### ISSUE TITLE
Camp.yml template is not according docker descriptors on Citygo use case

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/camp#80]
#### Characteristics

-   **Issue Type**: feature
-   **Reproducibility**: always
-   **Severity**: crash
-   **Tool/Service/Component**: 

> CAMP v0.6.2-git.bb86759 (MIT)
   Copyright (C) 2017 -- 2019 SINTEF Digital

-   **Execution Environment**: \[platform, OS, etc]
-   **Reporter**: fernando.mendez@atos.net - Fernando Mendez 

#### Description

Have to set up **camp.yml** according Citygo docker descriptors dependencies.

root@osboxes:/home/osboxes/Desktop/STAMP/camp/samples/stamp/atos# tree -L 3
.
├── camp.yml
├── Citygo
│   ├── apache
│   │   ├── demo_site.conf
│   │   ├── docker-compose.yml
│   │   ├── Dockerfile
│   │   ├── mpm_event.conf
│   │   └── requirements.txt
│   ├── app
│   │   └── backend
│   ├── nginx
│   │   ├── docker-compose.yml
│   │   └── nginx
│   ├── Postgres
│   │   ├── Dockerfile
│   │   ├── init-db.sql
│   │   └── postgresql.conf
│   └── Tests
│       └── citygo_tests
├── README.md
└── template
    ├── apache
    │   ├── demo_site.conf
    │   ├── Dockerfile
    │   └── mpm_event.conf
    ├── browser
    │   ├── Dockerfile
    │   └── tests.py
    ├── citygo
    │   └── Dockerfile
    ├── docker-compose-apache-as-proxy.yml
    ├── docker-compose-apache.yml
    ├── docker-compose-nginx.yml
    ├── nginx
    │   ├── Dockerfile
    │   └── nginx.tmpl
    ├── postgres
    │   ├── Dockerfile
    │   ├── init-db.sql
    │   └── postgresql.conf
    └── python
        └── Dockerfile

16 directories, 26 files

#### Steps to reproduce

**docker exec -i camp sh -c cd samples/stamp/atos/ && camp realize -d . && cp -R out/ /stamp_docker_citygoApp/**
CAMP v0.6.2-git.bb86759 (MIT)
Copyright (C) 2017 -- 2019 SINTEF Digital

Loaded './camp.yml'.
Loading configurations from './out' ...

Error:
Vain substitution: No match found!'
pattern: 'FROM\s+camp/[a-zA-Z0-9\._-]+(?:\:[a-zA-Z0-9\._-]+)?'
target file: './out/config_1/images/citygo_0/Dockerfile'
Is the pattern appropriate? What about the file content?

That's all folks!
exit

#### [Help on issue template](https://github.com/STAMP-project/eclipse-ide/blob/master/.github/ISSUE_DOC.md)
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by fchauvel** [comment]
Hi,

I just adjust the docker-compose files that were still referencing a component named `dashboard`, instead of the component named `citygo`. I see as well that several Dockerfile are still empty or with some simple instructions I placed there (see the [README file](https://github.com/STAMP-project/camp/blob/master/samples/stamp/atos/README.md)).  Unfortunately, without the source code I don't know how to further help debugging the `camp execute` part.

As for the two alternative cases, one being on performance tests and the other on functional tests, I created two subdirectories in the `samples/stamp/atos` directory. I created the templates I believe are relevant, but I would be grateful if you could check to ensure we have a shared understanding here.

Hope this helps.
